"""empty message

Revision ID: 7d3104670933
Revises: e14c258c53f0
Create Date: 2016-06-19 04:13:37.595140

"""

# revision identifiers, used by Alembic.
revision = '7d3104670933'
down_revision = 'e14c258c53f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zbhost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmdb_hostid', sa.Integer(), nullable=True),
    sa.Column('hostid', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=30), nullable=True),
    sa.Column('ip', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zbhost_cmdb_hostid'), 'zbhost', ['cmdb_hostid'], unique=True)
    op.create_index(op.f('ix_zbhost_hostid'), 'zbhost', ['hostid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zbhost_hostid'), table_name='zbhost')
    op.drop_index(op.f('ix_zbhost_cmdb_hostid'), table_name='zbhost')
    op.drop_table('zbhost')
    ### end Alembic commands ###
