"""empty message

Revision ID: dfda9c3766fe
Revises: d8b1a67b09af
Create Date: 2016-05-29 04:40:19.178594

"""

# revision identifiers, used by Alembic.
revision = 'dfda9c3766fe'
down_revision = 'd8b1a67b09af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idc', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_idc_status'), 'idc', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idc_status'), table_name='idc')
    op.drop_column('idc', 'status')
    ### end Alembic commands ###
